apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-ca-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /opt/local-path-provisioner/fabric-ca
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - beelink-fabric
