apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-ca-pvc
  namespace: orgdcms
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca
  namespace: orgdcms
spec:
  replicas: 1
  selector:
    matchLabels: { app: fabric-ca }
  template:
    metadata:
      labels: { app: fabric-ca }
    spec:
      containers:
      - name: ca
        image: hyperledger/fabric-ca:1.5.13
        args:
          - sh
          - -c
          - fabric-ca-server start -b admin:adminpw --tls.enabled
        env:
          - name: FABRIC_CA_HOME
            value: /etc/hyperledger/fabric-ca-server
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
        ports:
          - containerPort: 7054
        volumeMounts:
          - name: data
            mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fabric-ca-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
  namespace: orgdcms
spec:
  selector: { app: fabric-ca }
  ports:
    - port: 7054
      targetPort: 7054

